### ISSUE TITLE
LoadError - cannot load such file -- razorpay/bad_request_error:

### ISSUE THREAD

**Issue by itsmephani** [Razorpay/razorpay-ruby#1]
![razorpay](https://cloud.githubusercontent.com/assets/8447782/6919421/670ba186-d7d4-11e4-8710-9f2942c81909.png)
Getting LoadError - cannot load such file -- razorpay/bad_request_error: when capture failed

in file lib/razorpay/request.rb
change 
require "razorpay/#{error['code'].downcase}"
to
require "razorpay/errors/#{error['code'].downcase}"
now it is getting response error object

**Comment by captn3m0** [comment]
Thanks for the report. I've pushed a fix at version 1.0.2.

:+1:

**Comment by itsmephani** [comment]
Ok, No problem.
