### ISSUE TITLE
Razorpay::BadRequestError: The plan id field is required

### ISSUE THREAD

**Issue by imi56** [razorpay/razorpay-ruby#100]
While creating a subscription plan this error is thrown.
```
data = {
    :period => "monthly",
    :interval => 1,
        :item => {
            :name => "Monthly Rs.5,000.00",
          :amount => 500000,
        :currency => "INR"
    }
}
Razorpay::Subscription.create(data) // throws exception
# Razorpay::BadRequestError: The plan id field is required
```
The interesting outlook is the following request works for the same request data.
`Razorpay::Request.new("plans").post("", data)` 
I'm wondering how can plan id be required while creating the plan.
Help needed.

**Comment by ankitdas13** [comment]
Hi @imi56 apologise for the long delay. I hope this issue has been fixed. when creating a subscription, `plan_id` must be provided. 
Refer to this [document](https://razorpay.com/docs/api/payments/subscriptions/#request-parameters-2) for further information. Please let us know if you need any help

**Comment by ankitdas13** [comment]
Closing this issue for now due to not getting any response. If you need any help then, please let us know
