### ISSUE TITLE
Proper language specific documentation missing.

### ISSUE THREAD

**Issue by abnair1982** [razorpay/razorpay-ruby#119]
I was searching for documentation for routes(https://razorpay.com/docs/api/route/). All examples are for curl. 

It would be great if you could provide documentation specific to the language. For example a proper documentation for ruby gem, python  package etc. In your document pages you have given following examples for ruby
1) For fetching payments:
Razorpay::Payment.fetch("pay_29QQoUBi66xm2f")
2) For refund
Razorpay::Payment.fetch("pay_DgExayLn3RBbZX").refund()

I could not find documentation for:
1) What are the return value of these methods. 
2) What kind of exceptions are raised or thrown by these methods?
3) Method documentations for Payment and other classes.

Kindly provide language specific documentation for ruby, python and other languages.

**Comment by ankitdas13** [comment]
Hi @abnair1982 apologise for the long delay. The documentation for all SDK'S is provided on a regular basis as of now. You can also find the supported API'S code snippet inside the documents folder, it includes all parameters and response.

**Comment by ankitdas13** [comment]
Closing this issue for now if you need any help then, please let us know
