### ISSUE TITLE
Httparty 0.13 Dependency issue

### ISSUE THREAD

**Issue by guinex** [razorpay/razorpay-ruby#12]
We are using httparty 0.8 and razorpay has dependency on 'httparty', '~> 0.13'
Therefore I`m getting an error while installing bundle. Changing the dependency to httparty 0.8 solves my problem!. Will this change affect any other aspect?

**Comment by captn3m0** [comment]
HTTParty `0.8.0` was released September 13, 2011.

I wouldn't recommend relying on such an old version.
