### ISSUE TITLE
'method' seems to be reserved in rails

### ISSUE THREAD

**Issue by arpansac** [razorpay/razorpay-ruby#13]
While accessing 'method' using razorpay_response.method it gives an error: ArgumentError Exception: wrong number of arguments (given 0, expected 1)

I think it should be changed or probably another solution is needed!

**Comment by captn3m0** [comment]
Payment.method was fixed a while back: https://github.com/razorpay/razorpay-ruby/blob/master/test/razorpay/test_payment.rb#L25

**Comment by arpansac** [comment]
That doesn't seem to work, I still have to use payment.method_missing(:method) instead of payment.method

**Comment by captn3m0** [comment]
We need to push out a new release. Should be out by tonight :+1:

**Comment by captn3m0** [comment]
Pushed out https://rubygems.org/gems/razorpay/versions/1.2.0

**Comment by arpansac** [comment]
Long time, forgot to say thanks for the instant support @captn3m0 !
