### ISSUE TITLE
Not able to use order API

### ISSUE THREAD

**Issue by manuqwe** [razorpay/razorpay-ruby#16]
Says Razorpay::Order is uninitialized constant, however the Razorpay::Payment is working fine.

**Comment by akshaybhalotia** [comment]
Hi @manuqwe 

Please add `require 'razorpay/order'` to the file `razorpay.rb` and it should work.

We have fixed this in our code and would be soon releasing an updated gem with this fix.

**Comment by manuqwe** [comment]
Thanks Akshay,

Works like a charm, please add in the documentation. (y)

**Comment by akshaybhalotia** [comment]
No need for that @manuqwe , we are going to update the gem very soon.
