### ISSUE TITLE
Handle server being unrechable

### ISSUE THREAD

**Issue by captn3m0** [razorpay/razorpay-ruby#18]
We should raise a ServerError in such cases?

**Comment by akshaybhalotia** [comment]
You mean 5xx?

**Comment by captn3m0** [comment]
5xx is already handled. API returns a error key in that case, and we parse it correctly. Pasting a error report we received:

<details>
<summary>undefined method `key?` for nil:NilClass</summary>

When we are trying to get payment object to mark it capture using this code 
`Razorpay::Payment.fetch(pmt_id) `
We got this error "undefined method `key?' for nil:NilClass"

Here is the trace of error with line number

```
lib/razorpay/request.rb:62:in `create_instance' 
lib/razorpay/request.rb:48:in `request' 
lib/razorpay/request.rb:26:in `fetch' 
lib/razorpay/payment.rb:15:in `fetch'
```
</details>
