### ISSUE TITLE
NameError: uninitialized constant Razorpay::Customer

### ISSUE THREAD

**Issue by Samarththebox** [razorpay/razorpay-ruby#20]
When I write on console..

customer = Razorpay::Customer.create email: 'test@abc.com', contact: '9876543210'

it shows me an error: NameError: uninitialized constant Razorpay::Customer

**Comment by captn3m0** [comment]
Please put `require 'razorpay/customer` before where you want to use the customer class

**Comment by Samarththebox** [comment]
Thanks @captn3m0 Ideally razorpay class should load all nested classes.

**Comment by captn3m0** [comment]
Agreed, we faced the same issue with #10 earlier. Will try to take care of this from future releases.

Will close this once I push out a new release for this

**Comment by Samarththebox** [comment]
Even I can create a PR for that.. will add `require 'razorpay/customer'` and `require 'razorpay/invoice'` to razorpay.rb

**Comment by captn3m0** [comment]
Feel free to :100: 

I can merge and push out a new release :+1:

**Comment by harman28** [comment]
Fixed in #21
