### ISSUE TITLE
Unable to access certain classes within Razorpay module

### ISSUE THREAD

**Issue by sridharraman** [razorpay/razorpay-ruby#27]
Certain classes, such as `Invoice`, `Card`, `Customer` within the Razorpay module as not accessible.

I get the following errors:
NameError: uninitialized constant Razorpay::Card
NameError: uninitialized constant Razorpay::Invoice
NameError: uninitialized constant Razorpay::Customer

The other classes, such as `Order`, `Payment`, etc. are working fine.

I tried going through the code, but couldn't find out why. Any ideas?

**Comment by captn3m0** [comment]
The latest master is not yet released. We've tacked this recently, and you have two options:

1. Wait for our new release which should be out in a couple of days.
2. Implement our suggested fix (require `razorpay/{order|customer|invoice}`). See #9, #16 for previous discussions.

Card was not present in the 1.2.1 release: https://github.com/razorpay/razorpay-ruby/tree/1.2.1/lib/razorpay, so if you are looking to use it today, you will have to install the gem from github.

**Comment by sridharraman** [comment]
Thanks @captn3m0 

I will use the second option.
