### ISSUE TITLE
verify_payment_signature doesn't work. Use Rack::Utils secure compare instead.

### ISSUE THREAD

**Issue by mrudult** [razorpay/razorpay-ruby#31]
The [secure_compare](https://github.com/razorpay/razorpay-ruby/blob/master/lib/razorpay/utility.rb#L33) I think is faulty. I might be wrong.
I tried using the `verify_payment_signature` method provided by the library to verify my signatures from `Orders API` but it would always raise `SecurityError` error.

I wrote the verify_signature method myself (which I had previously written for Webhook checksum verification) and it works fine. Modified the same to work with `Orders API`. The snippet is below:

```
# Verification method for Razorpay Orders API Signature
def self.verify_signature(data)
    signature = data[:signature]
    order_id = data[:order_id]
    payment_id = data[:payment_id]
    data = [order_id, payment_id].join('|')
    calculated_hash = OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), ENV['RAZORPAY_SECRET'], data).strip()
    return Rack::Utils.secure_compare(calculated_hash,signature)
 end

# Verification method for Razorpay Webhook Checksum
def verify_signature(received_hash,data)
  calculated_hash = OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), ENV['RAZORPAY_WEBHOOK_SECRET'], data).strip()
  return Rack::Utils.secure_compare(calculated_hash,received_hash)
end
```

Hope it helps. 😄

**Comment by captn3m0** [comment]
We can't rely on Rack, since not everyone will have it. Thanks for the report, I'll be looking into this

**Comment by harman28** [comment]
@mrudult Sorry for the lack of response here. Are you still getting this error?
