### ISSUE TITLE
Razorpay::Payment object status improvement

### ISSUE THREAD

**Issue by gadikotamohan** [razorpay/razorpay-ruby#4]
When I capture authorized payment or refund captured payment from Razorpay::Payment object status is not changed.

for example

``` ruby
obj = Razorpay::Payment.fetch(raz_payment_id)
obj.status # outputs: "authorized"

obj.capture({amount: 100}) // assume 100 is amount authorized.
obj.status # outputs: "authorized", it should be "captured"
obj.refund
obj.status # outputs: "captured", it should be "refunded"
```

because of this I had to request razorpay api multiple times to check the status, if this is resolved I could minimize request to razorpay api.

**Comment by captn3m0** [comment]
Sounds reasonable.

**Comment by harman28** [comment]
Finally sorted with the introduction of bang! methods in #44
