### ISSUE TITLE
Razorpay capture payment

### ISSUE THREAD

**Issue by binkkatal** [razorpay/razorpay-ruby#40]
Is there any possibility that during payment capture any error will occur??

**Comment by akshaybhalotia** [comment]
Yes, there could be errors. Examples are authorization error due to invalid keys, or amount mismatch between payment request and capture request.

**Comment by binkkatal** [comment]
Are there any other cases apart from the above mentioned errors on production?

**Comment by akshaybhalotia** [comment]
Though rare, there could be. May I ask what do you need this for, as in what kind of functionality are you trying to build on this? This would help us answer your question better.

**Comment by binkkatal** [comment]
Its for the negative case that in case if the capture fails or gives an error , i can opt for an option to retry again in the app

**Comment by akshaybhalotia** [comment]
In such cases, you can check for the response code. Anything other than 200 is an error, and would certainly require human eyes. Hence, setup an alert on anything other than 200 and log the field `error_description`. This description is quite helpful, and most of the times helps resolve the error.

**Comment by binkkatal** [comment]
The explanation answers my query ,
Thanks for the help Akshay :)
