### ISSUE TITLE
Need a provision to create/update subscription using the gem

### ISSUE THREAD

**Issue by pbharadiya** [razorpay/razorpay-ruby#53]
Hi,
We are testing out razorpay as our payment gateway. One of the features that we seek is subscription creation and updating using ruby-gem. Is it possible to do so?

**Comment by pikender** [comment]
@pbharadiya Subscriptions Apis are still not part of official SDK yet but there is a [PR](https://github.com/razorpay/razorpay-ruby/pull/48) pending to be merged for the support.

In the meanwhile, you can use my [fork](https://github.com/vibrantstack/razorpay-ruby/tree/f/subscriptions) to get you started.

Adding below in your Gemfile should activate the needed magic :)

```
# Gemfile

gem 'razorpay', github: 'vibrantstack/razorpay-ruby', branch: 'f/subscriptions'
```

Refer above [PR](https://github.com/razorpay/razorpay-ruby/pull/48) description for the [Usage](https://github.com/razorpay/razorpay-ruby/pull/48#issue-278368033)

**Comment by harman28** [comment]
Hi @pbharadiya 
Subscriptions support will be added to this gem shortly (we're aiming for a release this week), thanks to the efforts of @pikender. If you'd rather not wait, please feel free to use [mentioned fork](https://github.com/vibrantstack/razorpay-ruby/tree/f/subscriptions), but please keep checking back in for updates!

**Comment by harman28** [comment]
Added in [v2.2.0](https://github.com/razorpay/razorpay-ruby/releases/tag/2.2.0)
