### ISSUE TITLE
Routes API

### ISSUE THREAD

**Issue by leenasn** [razorpay/razorpay-ruby#55]
How can I initiate the [Routes API] (https://razorpay.com/docs/route/api-reference/) through this gem? I want to initiate a transfer for a payment as mentioned in the API:

https://razorpay.com/docs/route/api-reference/#funds-movement-in-linked-accounts

Thanks,
Leena

**Comment by pikender** [comment]
@leenasn Route Api endpoints are not part of official SDK yet.

You can take inspiration from [here](https://github.com/razorpay/razorpay-ruby/pull/45/files#diff-9c197929ec3af958ad9e3e0096e981baR38)

Let me know if that helps :)

**Comment by srikanthcx** [comment]
Hi @leenasn,
I want to use Route API service using this gem. Can u please provide some sample code how we can create a transfer request from this gem.

I have tried with above solution, here my code.

`Razorpay::Payment.fetch(payment_id).create_transfer(account_id: transfer_id, amount: 8000)`

I was getting below error.
Razorpay::BadRequestError: account_id, amount is/are not required and should not be sent

Thanks,
srikanth

**Comment by leenasn** [comment]
Hi @srikanthcx I didn't the PR as @pikender suggested. Instead used HTTP calls. The params I am passing are:

- transfers[0][account]
- transfers[0][amount]
- transfers[0][currency]

Hope this helps.

**Comment by srikanthcx** [comment]
Thanks, @leenasn

**Comment by Nisthar** [comment]
@leenasn My question is not related to this library. But is there a way to create linked accounts via api rather than adding them manually?

**Comment by srikanthcx** [comment]
@Nisthar Razorpay don't have API for the accounts creation.

**Comment by Nisthar** [comment]
@srikanthcx thats bad. its useless without an api.

**Comment by harman28** [comment]
@Nisthar We'd expected that accounts are generally created asynchronously and used in your app later. If you need to create accounts in bulk, that too is doable via the portal. 

However, if you're having to create accounts in real-time, then this might be a new use case that we'd like to know more about. Would you mind raising this request on [our support portal](https://razorpay.com/support/)? We can take it from there.
