### ISSUE TITLE
Need a provision to charge customer's card on failed subscription

### ISSUE THREAD

**Issue by pbharadiya** [razorpay/razorpay-ruby#58]
Hello Team,

We want to charge customer's card after it is authenticated. Scenario could be when there is a failed subscription.

Let me know if there is already a way to achieve this.

**Comment by pikender** [comment]
@pbharadiya https://razorpay.com/docs/subscriptions/testing/#manually-charging-an-invoice

I guess you have already seen the above but still adding as reference. Currently, charging the failed subscription is manual and Razorpay dashboard has to be used. Though, Razorpay has plans to add an api for same but no known ETA for it

Let me know if above answers your question or give me more context, may be I can be of help :+1: 

cc/ @harman28

**Comment by pikender** [comment]
@pbharadiya did above helped ?

**Comment by harman28** [comment]
As @pikender said, the current way to do this is via manual charge of an older invoice via dashboard. 

Closing the issue due to inactivity.
