### ISSUE TITLE
OpenSSL error on OS X

### ISSUE THREAD

**Issue by mrudult** [razorpay/razorpay-ruby#6]
`OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed`

Tried almost everything. Updating certs from RVM, Homebrew as well as reinstall Ruby with RVM.

**Comment by captn3m0** [comment]
Thanks for the report. I'll take a look at this. If you could give your Ruby, rvm, and OS X versions that would be nice.

**Comment by mrudult** [comment]
Ruby - `ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]`
RVM - `rvm 1.26.11 (latest)`
OS X - `10.11.3 (15D21)`

**Comment by captn3m0** [comment]
Thanks a lot. I'm able to reproduce the bug with the same Ruby version. Will take a look tomorrow and figure out why it's failing.

**Comment by mrudult** [comment]
It works fine on Ubuntu with the same Ruby version.

**Comment by captn3m0** [comment]
I'm going to bundle the ca-certificate file since it seems httparty can't find it reliably on OS X.

**Comment by mrudult** [comment]
Also why not provide an option of `verify: false` in the HTTParty request option.

**Comment by captn3m0** [comment]
That is terribly insecure.

**Comment by mrudult** [comment]
It works now!
Thanks for the quick patch.

Can you publish the updated gem?

**Comment by captn3m0** [comment]
I'm currently working on Ruby SDK support for the new orders API that we just announced. I'll release the updated gem with both tonight.

**Comment by captn3m0** [comment]
Just published `1.1.0`: https://rubygems.org/gems/razorpay
