### ISSUE TITLE
Virtual Account API not working  

### ISSUE THREAD

**Issue by vik-y** [razorpay/razorpay-ruby#62]
```
2.2.4 :038 > va = Razorpay::VirtualAccount.create(h)
Razorpay::BadRequestError: The requested URL was not found on the server.
	from /Users/vikas.y/.rvm/gems/ruby-2.2.4/gems/razorpay-2.2.0/lib/razorpay/request.rb:105:in `raise_error'
```
I am using razorpay gem version `2.2.0`

**Comment by vik-y** [comment]
Any idea what's wrong with this?

**Comment by harman28** [comment]
@vik-y Could you share the key id you're using to make this request? It appears that Smart Collect may not be enabled for this account. You should be able to enable this in test mode from your Razorpay dashboard.

**Comment by vik-y** [comment]
Yes, that's exactly what the issue was. Razorpay support helped us fix it within 24 hours. Thankyou.
