### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by sumandroid** [razorpay/razorpay-ruby#67]
Whenever I create subscription through the gem, subscription is created but there is an argument error that I get which says:

**ArgumentError: wrong number of arguments (given 2, expected 1),
from /Users/test/.rvm/gems/ruby-2.3.3@gor/gems/razorpay-2.3.0/lib/razorpay/entity.rb:17:in `method_missing'**

maybe you are passing two arguments to the method_missing method which is only expecting 'name'. 
Is there any webhook callback after the subscription is created that I am not handling?

**Comment by sumandroid** [comment]
Hey Harman,
I am using the create method of Subscription class simply like:
Razorpay::Subscription.create(plan_id: 'plan_AXR7uMtDezLa234',
                                                      start_at: 1532700506,
                                                      total_count: 120,
                                                      customer_notify: 1)
and in return i get the following response:
**ArgumentError - wrong number of arguments (given 2, expected 1):
  razorpay (2.3.0) lib/razorpay/entity.rb:17:in `method_missing'**
Though the subscription is getting successfully created.

**Comment by harman28** [comment]
@sumandroid Tried checking our logs for your request, but couldn't find any. On a related note, the plan_id you're sending appears to be invalid, in that it does not exist in live or test mode. Could you share your merchant id so I can have a look at all of your requests?

We could also move this conversation to a mail thread with support@razorpay.com if you prefer that.

**Comment by sumandroid** [comment]
@harman28 I tried creating the subscription through restclient post API call to razorpay. It was successful.

**Comment by harman28** [comment]
Alright. Closing this, please feel free to reopen if you face issues or you could write to us too.
