### ISSUE TITLE
Payment link create API requiring line_items

### ISSUE THREAD

**Issue by mahidharc** [razorpay/razorpay-ruby#70]
I'm using the razorpay 2.3.0 gem. When I try to create a payment link, it gives me an error.

```
Razorpay::Invoice.create type: 'link', description: 'test description', amount: 100, currency: 'INR', customer: {name: 'Test', email: 'test@example.com'}
```

This gives me the following error.

```
Razorpay::BadRequestError: line_items is required.
```

However, the [documentation](https://razorpay.com/docs/payment-links/api/#creating-payment-links) for this does not specify anything regarding line items. Please let me know how I can  modify my request, so that I can generate payment links.

**Comment by radhika-tk** [comment]
@mahidharc : Thanks for bringing this to our attention. Will update you soon on this.

**Comment by arun-okcredit** [comment]
Hi,
I'm facing the same problem trying to create a payment link. Please let me know the status.

**Comment by mahidharc** [comment]
Hey,

Right now I am not using the SDK in our project. I'm just calling the REST API directly using RestClient, since that seems to be working properly.

But if you need any information regarding the context of the SDK, then I can provide you with more information. I tried using the `Razorpay::Invoice.create` method in IRB directly, after initializing the SDK, and that was the error I received. If you need anything else, then please let me know.

**Comment by arun-okcredit** [comment]
Thanks a lot.
-
Arun

**Comment by vjnvisakh** [comment]
"line_items": is/are not required and should not be sent

What is this.
Getting is this while creating invoice.

**Comment by harman28** [comment]
@mahidharc 

- Are you facing this kind of error only for invoice creation requests, or for all requests sent using this gem?
- Are you explicitly setting `Razorpay.headers` anywhere in your code, and are you overriding the `Content-Type` header? If so, what value are you using?

**Comment by harman28** [comment]
@arun-okcredit Same questions^ for you. I suspect you're setting content type explicitly to application/json (or something else) somewhere in your code, which is stopping the server from being able to read the input. 
This is supported by the fact that the error you're getting is the same as what you'd get if you sent a completely empty request.

For now, try removing the explicit setting of `Content-Type`. In future versions, I think we can consider actually blocking the setting of content type in custom headers to avoid this issue affecting others.

**Comment by harman28** [comment]
Closing this, as I think it's the same as the issue described in #77. Try [this](https://github.com/razorpay/razorpay-ruby/issues/77#issuecomment-481141633) and that should clear this up.

If anyone's still facing this error and removing Content Type doesn't help, please feel free to reopen the issue.
