### ISSUE TITLE
`verify_payment_signature` always return `nil`

### ISSUE THREAD

**Issue by dharshann** [razorpay/razorpay-ruby#73]
Here is my `verify_payment_signature` input. I always end-up getting `nil` as verification state.

```
{
  :razorpay_order_id=>"order_BvgPKQILlFk38U", 
  :razorpay_payment_id=>"pay_BvgQ5qSaZ25U1U", 
  :razorpay_signature=>"1fc86eb3406b88bab55ef9dd245a8f7686bfaae8f37bda5dab650580297f8206"
}

status = Razorpay::Utility.verify_payment_signature(payment_response)
# nil
```

I can check payment state as **paid** 
```
order = Razorpay::Order.fetch('order_BvgPKQILlFk38U') 

 #<Razorpay::Order:0x0000562764aaa410 @attributes={"id"=>"order_BvgPKQILlFk38U", "entity"=>"order", "amount"=>100, "amount_paid"=>100, "amount_due"=>0, "currency"=>"INR", "receipt"=>"47", "offer_id"=>nil, "status"=>"paid", "attempts"=>1, "notes"=>{"note"=>"test500"}, "created_at"=>1550037084}>
```

And payment status is **captured**

```
order.payments

#<Razorpay::Collection:0x0000562764a87e38 @attributes={"entity"=>"collection", "count"=>1, "items"=>[{"id"=>"pay_BvgQ5qSaZ25U1U", "entity"=>"payment", "amount"=>100, "currency"=>"INR", "status"=>"captured", "order_id"=>"order_BvgPKQILlFk38U", "invoice_id"=>nil, "international"=>false, "method"=>"card", "amount_refunded"=>0, "refund_status"=>nil, "captured"=>true, "description"=>"Purchase Description", "card_id"=>"card_BvgQ5ss5xV8WwY", "bank"=>nil, "wallet"=>nil, "vpa"=>nil, "email"=>"test@test.com", "contact"=>"+9199999999", "notes"=>{"address"=>"Hello World"}, "fee"=>2, "tax"=>0, "error_code"=>nil, "error_description"=>nil, "created_at"=>1550037128}]}>
```

**Comment by darshand** [comment]
Found a pretty small bug and sent a PR

[https://github.com/razorpay/razorpay-ruby/pull/72](https://github.com/razorpay/razorpay-ruby/pull/72)

**Comment by harman28** [comment]
@dharshann This is the expected behaviour. The function isn't supposed to return anything usable, its purpose is to throw an exception if the verification fails. You can just call it in your code before using the payment response.

**Comment by dharshann** [comment]
@harman28  In ruby `nil` means to `falsy`. Expecting a verification method to return a `falsy` output would't mean action got failed?

**Comment by harman28** [comment]
I tried addressing that in my comment on the PR as well. The function doesn't return anything (nil is what you get if the method you're calling doesn't have an explicit return value), so you shouldn't be checking the response for truthy-ness or falsy-ness (as in `status = `). You should just call the method, and if executes successfully, carry on.

I understand that the README currently doesn't make this clear at all. I'll get that fixed.

**Comment by harman28** [comment]
On second thoughts, I see no actual harm in returning the verification status as well. Yes, it'll always return true, but as you said, that's a lot better than returning `nil`, which can be mis-interpreted.

Let's work on getting #72 merged :)

**Comment by dharshann** [comment]
Thanks @hemanth132 .
