### ISSUE TITLE
Error in creating a plan#The interval field is required.

### ISSUE THREAD

**Issue by Deena-D-Cutinha** [razorpay/razorpay-ruby#77]
![Screenshot from 2019-04-08 16-39-57](https://user-images.githubusercontent.com/32517541/55720466-877ac700-5a1e-11e9-8d24-40fa06adb6c0.png)

**Comment by harman28** [comment]
@Deena-D-Cutinha I'm not able to understand the problem from this screenshot. Could you add more details to the issue? Perhaps a sample of the code you were executing, or else instructions for how to reproduce it?

**Comment by Deena-D-Cutinha** [comment]
@harman28 When ever i try to create a plan it throws  a error saying interval is required.
code snippet:
plan = Razorpay::Plan.create interval: 1, period: 'monthly', item: { name: 'fake_plan', description: 'fake_desc', currency: 'INR', amount: 500 }, notes: { identifier: 'plan_monthly_super' }

**Comment by harman28** [comment]
Could you share your Ruby version, gem version, and Razorpay merchant ID?

**Comment by Deena-D-Cutinha** [comment]
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux],
gem razorpay (2.3.0)
Razorpay merchant ID: 9JqJdm7UwMGHPd

**Comment by harman28** [comment]
Not able to recreate this, even with the same setup. However, I did take a look at our production logs and saw that the requests we're receiving for this are completely empty.
<img width="328" alt="Screenshot 2019-04-09 at 12 55 38 PM" src="https://user-images.githubusercontent.com/4201494/55780988-ccf2cf00-5ac6-11e9-9059-9e44de2cff16.png">

Some more questions:
- Are you facing this kind of error only for plan creation requests, or for all requests send using this gem?
- Are you explicitly setting `Razorpay.headers` anywhere in your code, and are you overriding the `Content-Type` header? If so, what value are you using?

**Comment by Deena-D-Cutinha** [comment]
Thank you @harman28 
It worked.
I removed Razorpay.headers = {"Content-Type" => "application/json"}  from development.

**Comment by harman28** [comment]
Glad we were able to fix this.

**Comment by imdkbj** [comment]
Hi, I am using the Google App script to generate the payment but getting the same error of line times.

The following code worked.
`function loginflow(){
  var headers = {"Authorization" : "Basic " + Utilities.base64Encode(keyid + ':' + key)};
  var params = {
    method:"GET",
    headers:headers
  };
  var response = UrlFetchApp.fetch(encodeURI(url), params);
  Logger.log(response.getResponseCode());  
}`

But getting error on following code : 
Error is  -  {"error":{"code":"BAD_REQUEST_ERROR","description":"line_items is required."}}
 


`function razorpay(){
var url= 'https://api.razorpay.com/v1/invoices';
  var headers = {"Authorization" : "Basic " + Utilities.base64Encode(keyid + ':' + key)};
  var options = {
    "method": "POST",
    "headers": headers,    
    "customer": {"name": "Deepak","email": "test@test.com","contact": "9999999999"},
    "type": "link",
    "view_less": 1,
    "amount": 1000,
    "currency": "INR",
    "description": "test",
    "expire_by": 1493630556
  };
  var response = UrlFetchApp.fetch(url, options);
  Logger.log(response.getContentText());
}
`

**Comment by harman28** [comment]
@imdkbj The error is what you'd get if you sent a blank request for invoice creation. Your first example works because there's no body for the GET request. Your second example has the creation body mixed up with the options for `UrlFetchApp.fetch`, which is why I think it's failing. You should be sending the creation request under `options['payload']`.

If your problem persists, could you report it [here](https://razorpay.com/support/#request) and let us get back to you? It doesn't seem related to this Ruby gem.

**Comment by shivi-tyagi** [comment]
{
"customer":{
"contact":"7807278763",
"name":"shivi",
"email":"shivi.tyagi@squadrun.co"
},
"description":"For more information about Teleconference and Counseling process please click https://isaglobal.in/tele1.aspx",
"email_notify":1,
"currency":"INR",
"amount":10000,
"expire_by":1793630556,
"view_less":0,
"sms_notify":1,
"type":"link"
}

if i am using 1 in view_less it gives me the same error. can you please help here. Although for months i have using it like this only. i am receiving this error since last few days only.

**Comment by shivi-tyagi** [comment]
<img width="1442" alt="Screenshot 2020-10-20 at 3 21 29 PM" src="https://user-images.githubusercontent.com/73168204/96570465-09240400-12e8-11eb-9e67-7a33c40c4b30.png">

**Comment by shivi-tyagi** [comment]
{
    "customer":{
"contact":"7807278000",
"name":"shivi",
"email":"shivi.tyagi@gmail.com"
},
"description":"For more information about Teleconference and Counseling process please click https://google.com",
"email_notify":1,
"currency":"INR",
"amount":100,
"expire_by":1793630556,
"view_less":0,
"sms_notify":1,
"type":"link"
}

**Comment by shivi-tyagi** [comment]
I am facing this issue since last few days. instead of 0 in view_less if i write 1 then it is successful. 

@harman28 can you please help here.

**Comment by imdkbj** [comment]
Able to reproduce the error, It's a bug.

**Comment by sriramraja2** [comment]
@shivi-tyagi can you share the endpint you are using? also the MID. if you are using - https://api.razorpay.com/v1/payment_links/ - `type` and `view_less` are not needed. New contract - https://razorpay.com/docs/payment-links/api/new/create/ .

Share your MID also - I can recon internally.

**Comment by shivi-tyagi** [comment]
End Point : https://api.razorpay.com/v1/invoices/

sorry not sure how i can share the MID! can you guys point it out to me in the right direction here

**Comment by sriramraja2** [comment]
In the legacy contract - view_less as 0 has had issues before. I would advise you to use the new contract - https://api.razorpay.com/v1/payment_links/ . Docs are at - https://razorpay.com/docs/payment-links/api/new/create/ . The. migration process is underway - you can still use it till Dec 31 2020 but at sometime you have to switch. The changes are limited and don't change the business logic.

**Comment by shivi-tyagi** [comment]
@sriramraja2 this answer is quite unacceptable _**In the legacy contract - view_less as 0 has had issues before. I would advise you to use the new contract -**_

Without any proper notification our working API's stopped working. 

In case of migration should we not get any prior notification. Our client’s API were falling resulting in serous business loss.

**Comment by sriramraja2** [comment]
@shivi-tyagi if you can share your MID - I can find out if any migration happened on your account. We can revert you to the earlier system in which you don't have to change a single key on your system. The integration will be as-it-is on the older system.

**Comment by sriramraja2** [comment]
@shivi-tyagi from what I see - view_less: 0 - would not have worked at any point in time. do let me know if you had an earlier successful integration with view_less as 0.

**Comment by shivi-tyagi** [comment]
Yes we were using the same payload for 1 - 2 months now. 

https://github.com/razorpay/razorpay-ruby/issues/77#issuecomment-712935096

**Comment by sriramraja2** [comment]
@shivi-tyagi it will help us to debug the issue if you can share MID - we can rule out accoutn specific issues as well. you can email here - apps-apimigration@razorpay.com  . I will use the MID to also check the incoming API requests with teh view_less and accordingly debug from there.

**Comment by shivi-tyagi** [comment]
Have sent the MID in email.

**Comment by sriramraja2** [comment]
Thanks
