### ISSUE TITLE
payment.method does not work properly

### ISSUE THREAD

**Issue by captn3m0** [razorpay/razorpay-ruby#8]
Since Ruby has a `method` method on the [Object class](http://ruby-doc.org/core-2.2.3/Object.html#method-i-method), trying to call `payment.method` to get the payment method (card|...) does not work properly.

A workaround is to do the following:

```
payment.method_missing(:method)
```

**Comment by vamsipavanmahesh** [comment]
The exact error is wrong number of arguments 0 for 1.

**Comment by captn3m0** [comment]
A possible solution is to override the `method` method itself in our Class. However, that would make our class slightly less extendable.

**Comment by captn3m0** [comment]
This was closed with https://github.com/razorpay/razorpay-ruby/commit/87ec9304f23d829431eb893c76da142d74e19b29
