### ISSUE TITLE
Error while creating a invoice

### ISSUE THREAD

**Issue by Deena-D-Cutinha** [razorpay/razorpay-ruby#83]
I am able to create a invoice with the type 'link' as per the syntax given.
But when i try to change the type to 'invoice' it throws a error.

code snippet:
invoice = Razorpay::Invoice.create type: 'invoice',customer_id: "cust_CHYKFUnfRjWbEj", line_items: [{item_id: "item_CHYCYqNuYFviS2" }], currency: 'INR',sms_notify: "1",email_notify: "1"

**Comment by harman28** [comment]
@Deena-D-Cutinha What is the error message in the response you are receiving? Usually the message is enough to explain what the issue might be. Let me know if this is not the case.

**Comment by Deena-D-Cutinha** [comment]
Error:invoice can only use item of one of following types: invoice

**Comment by harman28** [comment]
Hope that clears it up then. The line_item that you're using (`item_CHYCYqNuYFviS2`) here is an item of type 'plan'. You can only use items of type 'invoice' while creating an invoice.

I've noted that this is not explicitly mentioned in the documentation for [creating an invoice](https://razorpay.com/docs/invoices/api/#creating-an-invoice). I'll try and get that updated.
