### ISSUE TITLE
Create a Fetch All Plans method for RoR

### ISSUE THREAD

**Issue by abizerlokhandwala** [razorpay/razorpay-ruby#85]

**Comment by harman28** [comment]
@abizerlokhandwala Is `Razorpay::Plan.all` not working for you?

**Comment by abizerlokhandwala** [comment]
Was not mentioned in the documentation, did not know that it works. It would be great if you added a list of functionalities and methods that do work for RoR, thanks!

**Comment by harman28** [comment]
You're right, there are quite a lot of functions not mentioned in the README. I'll try and get them added, or if you get time you're welcome to raise a PR as well. Thanks again!
