### ISSUE TITLE
Razorpay::Utility.verify_webhook_signature not working as expected

### ISSUE THREAD

**Issue by saurabhnanda** [razorpay/razorpay-ruby#89]
Requestbin - http://requestbin.net/r/zqlgjlzq?inspect

```
irb> rp = '{"entity":"event","account_id":"acc_CEOgayStbojn2W","event":"refund.created","contains":["refund"],"payload":{"refund":{"entity":{"id":"rfnd_DzcgZ2NB9jkUsY","entity":"refund","amount":22500,"currency":"INR","payment_id":"pay_DzcPVgs5suYXTd","notes":{"comment":""},"receipt":null,"acquirer_data":{},"created_at":1577971510}}},"created_at":1577971510}'
irb> sig = '71b7f3f610ffd99819d8aa1712d909c2a77f7e88dae7283700bf88a851ce99f5'
irb> secret = 'L26zm9kjbmx@JqH'
irb> Razorpay::Utility.verify_webhook_signature(rp, sig, secret)

SecurityError: Signature verification failed
```

PS: The secret is from our test account.

**Comment by saurabhnanda** [comment]
Is this happening because of `@` in the secret?

**Comment by captn3m0** [comment]
Likely happening because you are parsing the JSON body, and then converting it to JSON again.

Please ensure that the `rzp` variable here is coming straight from your response body.

**Comment by saurabhnanda** [comment]
using `request.raw_post` in the actual code.

**Comment by saurabhnanda** [comment]
Also, in the code shared above, it can be seen that the raw string is being passed to the function.

**Comment by captn3m0** [comment]
Are you still facing this issue? Can you create a support ticket at razorpay.com/support please?

I took the same body/signature/secret tuple and tried it on our Python SDK and it fails there as well, so looks like unrelated to the ruby SDK.

**Comment by saurabhnanda** [comment]
It's because of `@` in the secret. We removed that and it worked.
